### ISSUE TITLE
Calibration_alm() for TE/ET spectra

### ISSUE THREAD

**Issue by beringueb** [simonsobs/syslibrary#16]
When we do this loop in Calibration_alm.eval():

```
for k1 in cal1.keys():
    c1=np.array(cal1[k1])[...,np.newaxis]
    for k2 in cal2.keys():
        c2=np.array(cal2[k2])
        if(k1==k2):
            cal[k1]=c1*c2
        else:
            cal['te']=c1*c2
```
(with cal1 and cal2 keys being "tt", "ee" in **that** order !) we are correctly writing cal['te'] for k1 = "tt" (c1 = temperature cals) and k2 = "ee" (c2 = polarization cals), and for k1 = "ee" (c1 = pol cals) and k2 = "tt" (c2 = temperature cals) we are overwriting cal['te'] with cal['et'] ! 

Proposed fixes:
- Explicitely check for wich spectra we are interested in ("te" or "et") and store them separately in `cal`)
- Having the input `cal` keys being "t" or "e" and concatenate them to create `cal["te"], cal["et"]`, ... . This would make more sense as they are alm level calibration anyway. But would require some (small) modification in MFLIKE as well.

**Comment by mgerbino** [comment]
Issue successfully addressed with PR #17 . Closing issue
